# config/default.yaml

experiments:
  # “smoke‐test” run on CPU/GPU (no DDP)
  - experiment_name: "smoke_test"
    dataset: "Cora"
    model: "gcn"
    epochs: 5
    batch_size: [16, 32, 64, 128, 256, 512]
    lr: 0.001
    hidden_dim: 64
    seed: 42
    world_size: 1
